apiVersion: apps/v1

kind: Deployment
metadata:
  name: runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runtime
  template:
    metadata:
      labels:
        app: runtime
    spec:
      ## Dashboard Runtime ##
      containers:
      - name: runtime
        image: leoomaia/cloud_my_runtime
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/opt/usermodule.py"
          subPath: pyfile
        env:
        - name: REDIS_HOST
          value: "192.168.121.66"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
      volumes:
      - name: pyfile
        configMap:
          name: pyfile