apiVersion: v1
data:
  REDIS_OUTPUT_KEY: leonardooliveira-proj3-output
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-12T19:28:19Z"
  name: outputkey
  namespace: leonardomaia
  resourceVersion: "4387973"
  uid: 293715db-8f7f-47ab-948f-e2721af93129
