name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  push_to_registry:
    name: Push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      
      - name: User and Token for Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CLOUDTP3_USERNAME }}
          password: ${{ secrets.CLOUDTP3_TOKEN }}
    
      - name: Build and Push image to change Dashboard container
        uses: docker/build-push-action@v4
        with:
          context: task2/dashboard/
          push: true
          tags: leoomaia/cloud_my_dashboard

      - name: Build and Push image to change Runtime container
        uses: docker/build-push-action@v4
        with:
          context: task3/runtime/
          push: true
          tags: leoomaia/cloud_my_runtime